---
- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Install Docker packages
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
    state: "{{ 'latest' }}"

- name: Ensure Docker data directory exists
  ansible.builtin.file:
    path: "{{ docker_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0710'

- name: Ensure specified users are in the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_group_members }}"
  when: docker_group_members | length > 0

- name: Ensure Docker configuration directory is present
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: u+rwx,g+rx,o+rx

- name: Ensure Docker daemon is configured
  ansible.builtin.template:
    src: 'daemon.json.j2'
    dest: '/etc/docker/daemon.json'
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: Restart Docker

- name: Enable Docker service
  ansible.builtin.service:
    name: docker
    enabled: true

- name: Ensure all handlers run before continuing
  ansible.builtin.meta: flush_handlers
