---
- name: Ensure outdated versions of Docker packages are absent
  ansible.builtin.package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: Add Docker RPM signing key
  ansible.builtin.rpm_key:
    key: "{{ docker_yum_gpg_key }}"
    state: present

- name: Add Docker YUM repository
  ansible.builtin.get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: "/etc/yum.repos.d/docker-{{ docker_edition }}.repo"
    owner: root
    group: root
    mode: "0644"

- name: Ensure netfilter kernel modules for Docker networking are installed
  ansible.builtin.package:
    name: "kernel-modules-extra-{{ ansible_facts['kernel'] }}"
    state: present

- name: Ensure netfilter kernel modules required by Docker are loaded
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - br_netfilter
    - ip_tables
    - xt_addrtype
